### ISSUE TITLE
Unbinding Events

### ISSUE THREAD

**Issue by jcblw** [honeinc/sidebar#20]
So there is probably some issues with this chunk of code

https://github.com/honeinc/sidebar/blob/master/index.js#L283
![screenshot from 2015-01-14 09 40 13](https://cloud.githubusercontent.com/assets/578259/5743935/6f475d8e-9bd1-11e4-9487-31200db128a2.png)

due to the `.bind` allways creating a new function I think moving this to use `bound` would fix it.

**Comment by andyburke** [comment]
yeah, at the least would need to retain previous bindings

**Comment by jcblw** [comment]
yeah thats what bound does internally, the only issue is the partial. Which there is a feature request I put on bound to support that.

**Comment by jcblw** [comment]
fixed  in #23
